# Generated by Django 4.0.6 on 2022-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingDragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitors', models.TextField(blank=True)),
                ('tickets', models.TextField(blank=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewDragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255)),
                ('technical_characteristics', models.TextField(blank=True)),
                ('produced', models.TextField(blank=True)),
            ],
        ),
    ]
